package ma.entraide.ramadan.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@Data
@Entity
public class Stock {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "delegation_id", nullable = false)
    private Delegation delegation;

    @ManyToOne
    @JoinColumn(name = "produit_id", nullable = false)
    private Produit produit;

    @Column(name = "quantite_max", nullable = false)
    private Integer quantiteMax;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Delegation getDelegation() {
		return delegation;
	}

	public void setDelegation(Delegation delegation) {
		this.delegation = delegation;
	}

	public Produit getProduit() {
		return produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Integer getQuantiteMax() {
		return quantiteMax;
	}

	public void setQuantiteMax(Integer quantiteMax) {
		this.quantiteMax = quantiteMax;
	}

	public Stock(Long id, Delegation delegation, Produit produit, Integer quantiteMax) {
		super();
		this.id = id;
		this.delegation = delegation;
		this.produit = produit;
		this.quantiteMax = quantiteMax;
	}

	public Stock() {
		super();
	}

    // Getters and Setters (automatically generated by Lombok)
}
